### ISSUE TITLE
The link for the pre-trained weight is invalid.

### ISSUE THREAD

**Issue by Houruizhi** [HJ-harry/score-MRI#4]
Hi,

The link for the pre-trained weight is invalid. Could you please provide the weights? I want to compare your work in my paper.

Best wishes.

**Comment by HJ-harry** [comment]
Apologies for the inconvenience. I'm not sure why the link is not working. Could you please directly accessing the below link?

https://www.dropbox.com/s/27gtxkmh2dlkho9/checkpoint_95.pth?dl=0

**Comment by Houruizhi** [comment]
您好，您的邮件我已经收到。

**Comment by Houruizhi** [comment]
This link works. Thanks for your helpful reply.

**Comment by MohammadVaziriCh** [comment]
This link also doesn't work now.
